### ISSUE TITLE
Vector podAffinity unschedulable

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#180]
Issues identified deploying vector to k8s:

- If a node in the cluster has no resources available to schedule a new vector pod, the autoscale will not trigger a new worker and the process will hang till resources are free for the vector pod creation.
- We cannot deploy multiple Aspects installation (probably) in the same cluster because the Vector DaemonSet will create a Vector pod for every node, which implies that:
`vector pods = number of nodes * number of openedx installations in cluster`

**Comment by Ian2012** [comment]
Possible solutions:
- Use a priorityClass so that k8s knows that vector has priority and must be on every worker node https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#example-priorityclass
- Use a deployment with podAffinity (didn't work for me)

**Comment by jfavellar90** [comment]
Here we have 2 different problems:

1) Daemonset scheduling problem: we need to make sure that we have space to schedule Vector nodes. In the case where the cluster is very short on resources on each node and the Vector Daemonset is triggered to be created, the scheduling of such will fail since cluster-autoscaler won't trigger the creation of a new node. To overcome this limitation we can use [Priority Classes](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass) in order to guarantee that Vector is scheduled with priority over other workloads. This way we prevent that cluster-autoscaler get blocked.

2) Make sure we schedule ONLY ONE POD per node with an LMS scheduled. This is because you run vector on every openedx namespace and the idea is to capture the tracking logs of every LMS pod from the installation. However, having a different Daemonset per namespace doesn´t seem to be the best option. We could have a global installation of Vector and make all the Click-house instances consume from that global Vector, but this approach poses different problems.

**Comment by Ian2012** [comment]
Another issue is that the current DaemonSet tries to mount the same volume many times which is not supported by k8s.


We should adapt our k8s resources for the [Vector Agent](https://vector.dev/docs/setup/deployment/roles/#agent) use case as implemented in this [helm chart](https://github.com/search?q=repo%3Avectordotdev%2Fhelm-charts+.Values.role+%22Agent%22&type=code)

**Comment by regisb** [comment]
@Ian2012 Looks like we need additional resources and verbs : https://github.com/vectordotdev/vector/blob/52ac10ac23fe120ac3e1c89ec3196be9ac894009/distribution/kubernetes/vector-agent/rbac.yaml#L17
Can you please try this out? If it works for you I'd also like to change the RBAC in Cairn.

**Comment by Ian2012** [comment]
Thanks @regisb, it solved the issue. There are other scenarios but I think it's better to discuss this via slack

**Comment by Ian2012** [comment]
This issue has been resolve by #179 and #209.

Multiple Aspects installations in the same cluster has not been tested. We can close this issue and open a new one 

@bmtcril

**Comment by regisb** [comment]
I strongly suggest you do not use an `emptyDir` to store Vector state. If you do, and the volume is deleted, then vector will either miss some events or collect some of them twice.

**Comment by Ian2012** [comment]
I was thinking about that scenario. Would a `statefulSet` be a better implementation?

Any other ideas?
