### ISSUE TITLE
Perf: Instructor Dashboard performance regressions

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#534]
In large scale load testing, the following Instructor Dashboard reports have poor performance, or are timing out:

- Currently enrolled learners per day 
  - This only seems to be slow when no course filter is applied, we could possibly force a course filter here)
- Transcripts / Captions per video
  - This is pulling directly from `xapi_events_all_parsed` and should probably have an intermediate model of just these events with associated "enabled" / "disabled" values parsed out

**Comment by SoryRawyer** [comment]
The transcripts chart should be backed by a smaller MV instead of the larger `xapi_events_all_parsed` table, so performance should be improved.
I haven't been able to get much more performance out of the enrolled learners per day dataset, so I think requiring a course filter would be a reasonable change to enhance performance.

**Comment by bmtcril** [comment]
I think choosing a course is going to be required for v1 anyway 👍  Calling this one done, we'll do another round of testing once we have a v1 RC.
