### ISSUE TITLE
Datasets are empty in SQL Lab

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#537]
In the SQL Lab, there is no way to inject filters unless the use of raw SQL, and filter values are checked to be defined in many datasets so that the instructor dashboard makes sense.

This causes the SQL Lab and the create chart view obsolete as we can't previsualize, nor query the database there.

The solution would be to verify the current context (dashboard, chart, or sqllab) and provide a corresponding default values for the where clauses

**Comment by bmtcril** [comment]
Can you give a specific example of how to trigger this and what you see? There are some privacy and security considerations for granting access to data that we may have to think through or document more explicitly if non-superusers are working in SQL Lab.

**Comment by Ian2012** [comment]
Create a chart for a dataset that requires filter values:

![image](https://github.com/openedx/tutor-contrib-aspects/assets/33465240/0dfb859f-9a47-470a-a0d0-0f94afef5c41)

Check that the visualization shows no data even if it's there

**Comment by bmtcril** [comment]
Right, I think those are explicitly set to not load the entire dataset if no filter is selected, otherwise the query will just time out anyway on a large dataset:

`{% if filter_values('video_name_with_location') != [] %} video_name_with_location in {{ filter_values('video_name_with_location') | where_in }} {% else %} 1=0 {% endif %}`

They could just temporarily change that to `1=1` on whatever virtual dataset they're working on locally to get all results for testing. Running this with 1=1 on a production environment can run the server out of memory and cause performance issues, so I'd like to avoid doing that by default. Plus it has some potential security / privacy issues we'd have to work through from a product perspective about how we want to support those features for non-superusers.

I don't know of a way to use the virtual datasets in SQL Lab, but I know there's a way to pass a filter value in the "..." menu -> Parameters and `_filters` that should help get past some of this: https://superset.apache.org/docs/installation/sql-templating/

**Comment by bmtcril** [comment]
@Ian2012 is this still an issue we need to work more on, or were the suggestions sufficient?

**Comment by Ian2012** [comment]
@bmtcril Yes, I can confirm we can close it now
